sudo: required
services: 
    - docker

before_install:
    - docker build -t appleliver/docker-react -f Dockerfile.dev .

script: 
    - docker run appleliver/docker-react npm run test -- --coverage
